
[MusicPlayer]
	#allow the music player to play boss themes
	"Music Player" = true
	#define which entity the boss music will follow.
	#Allowed Values: BOSS, PLAYER_CAMERA
	"Boss Music Location Type" = "BOSS"

["Alpha textures"]
	#Enables the dynamic alpha texture detector. This allows the mod to automatically identify generic alpha textures, but may cause performance drops (lag) during the render of alpha entities.
	"Enable dynamic alpha texture detector" = true

["Custom Hair Color"]
	#Set The Custom Hair Color For the Female Sneps [BioSynth and Exp2]
	"Females Sneps Custom Hair Color" = false
	#Set The Custom Hair Color For the Male Sneps [BioSynth and Exp2]
	"Males Sneps Custom Hair Color" = false

[Overlays]
	#Set the Pat Overlay On or Off
	"Pat Overlay" = true
	#Set the X pos of the pat overlay.  
	#[Default 12]
	"Pat Overlay X pos" = 12.0
	#Set the Y pos of the pat overlay.  
	#[Default 72]
	"Pat Overlay Y pos" = 72.0
	#Display How much Ticks You have Hold the Wing Flap Ability
	"Wing Flap Ability Ticks Info" = false
	#Make the pat overlay use a paw icon instead of text
	"Paw Style Pat Overlay" = true

["Extra Animations"]
	#allow the show of the extra hand in some contexts like fall fly
	"Show Extra Hand" = false
	#Make the Laser Moviment be smooth, it may cause the particule to be slower
	"Laser Smooth Moviment" = false

[ModelsHandle]
	#Turn off the Plantoids [Female Chest Features]
	"Turn Off the Plantoids" = false
	#Turn the Compatibility Mode Render For Alpha Scales, turning this off may add some performance
	"Alpha Compatibility Render Mode" = true

